name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - name: Install SARIF tools
      run: cargo install clippy-sarif sarif-fmt
    - name: Run clippy
      run: >
        cargo clippy --all-targets --message-format=json -- -D warnings
        | clippy-sarif
        | tee clippy-results.sarif
        | sarif-fmt
      continue-on-error: true
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: clippy-results.sarif
        wait-for-processing: true
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run rustfmt
      run: cargo fmt --all --check
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install prettier
      run: npm install --save-dev --save-exact prettier
    - name: Run prettier
      run: npx prettier --check '**/*.{css,html,js}'
  committed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Lint commits
      uses: crate-ci/committed@master
